/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jacekkowalczyk82.c2p;

import org.jacekkowalczyk82.c2p.Code2Present;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class Code2PresentTest {
    @Test void appHasAGreeting() {
        Code2Present classUnderTest = new Code2Present();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
