/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.jacekkowalczyk82.c2p;

import org.jacekkowalczyk82.c2p.model.*;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;


public class HowToPresentationFromJSONModel {


    public static void main(String[] args) {

        Presentation pres = JSONTools.readJSONToPresentation("how-to-presentation-input.json");


        Code2Present c2p = new Code2Present();
        System.out.println("This is How To example presentation ");

        c2p.fromTemplate(pres.getConfiguration().getFromTemplate());
        c2p.toPresentation(pres.getConfiguration().getTargetPresentationFile());
        c2p.setTitleRectangle(pres.getConfiguration().getTitleRectangle().toAWTRectangle());
        c2p.setSubTitleRectangle(pres.getConfiguration().getSubTitleRectangle().toAWTRectangle());

        c2p.setSlideTitleRectangle(pres.getConfiguration().getSlideTitleRectangle().toAWTRectangle());
        c2p.setSlideContentRectangle(pres.getConfiguration().getSlideContentRectangle().toAWTRectangle());
        c2p.setSlideFooterRectangle(pres.getConfiguration().getSlideFooterRectangle().toAWTRectangle());
        c2p.setFooterFontInfo(pres.getConfiguration().getFooterFontInfo());
        c2p.setFooterTemplate(pres.getConfiguration().getFooterTemplate());

        c2p.title(pres.getTitleSlide().getTitle(), pres.getTitleSlide().getSubTitle());

        for (Slide s: pres.getSlides()) {
            c2p.slide(s.getSlideTitle(), s.getContent(), s.getContentFontInfo());
        }

        try {
            c2p.save();
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
